# Generated by Django 6.0.3 on 2026-03-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
